type Boards {
  id: String!
  title: String!
  contents: String!
  users_id: Int!
  updated_at: String!
  created_at: String!
  is_deleted: Int!
  comments: [Comments]
}

input BoardInput {
  title: String!
  contents: String!
  users_id: Int!
}

type Query {
  boards: [Boards]
}

type Mutation {
  createBoard(input: BoardInput!): Boards
}